### ISSUE TITLE
Disable SSl verification

### ISSUE THREAD

**Issue by mlytvyn** [klaushauschild1984/jhac#20] opened 2021-03-15 11:54 UTC
```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://admin-hybris-qa.site.com/hac": Certificate for <admin-hybris-qa.site.com> doesn't match any of the subject alternative names: [ingress.local]; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for <admin-hybris-qa.site.com> doesn't match any of the subject alternative names: [ingress.local]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:751) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:586) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at com.sap.hybris.hac.Base.authenticate(Base.java:85) ~[jhac-core-1.0-alpha.4.jar:?]
	at com.sap.hybris.hac.Base.prepareRestTemplate(Base.java:72) ~[jhac-core-1.0-alpha.4.jar:?]
	at com.sap.hybris.hac.Base.execute(Base.java:53) ~[jhac-core-1.0-alpha.4.jar:?]
	at com.sap.hybris.hac.Base.execute(Base.java:46) ~[jhac-core-1.0-alpha.4.jar:?]
	at com.sap.hybris.hac.flexiblesearch.FlexibleSearch.query(FlexibleSearch.java:26) ~[jhac-core-1.0-alpha.4.jar:?]
```

p.s. Please release new version, it looks very promising!

**Comment by klaushauschild1984** [comment] 2021-03-15 18:56
Feel you.
WIll implement an option to disable SSL verification.

If you can wait a little longer a new release with all recent changes will be out.

**Comment by jlolling** [comment] 2021-03-15 19:07
Thats great. Often causing self certificates trouble. I usually add this feature optionally.

**Comment by klaushauschild1984** [comment] 2021-03-16 08:57
@mlytvyn I guess this is not the typical untrusted SSL certificate situation. If you take a look at `StatefulRestTemplate` there is already a trust strategy in place which will trust self-signed certificates.
I think this is related to the hostname verification and hostname `ingress.local` doe not match the actual hostname you are talking to.
Anyway I will try to fix this and push a relaxed version.

**Comment by klaushauschild1984** [comment] 2021-03-16 09:30
Please try this feature branch `feature/disable-ssl-verification` containing the fix.

**Comment by klaushauschild1984** [comment] 2021-03-16 09:31
Have a look at this PR
https://github.com/klaushauschild1984/jhac/pull/22

**Comment by klaushauschild1984** [comment] 2021-03-16 10:23
@mlytvyn please ping me if the problem is solved or other issues occur. On my side, I have no environment at hand to verify my fix. I have to rely on you.

**Comment by klaushauschild1984** [comment] 2021-03-18 08:37
Merged to `master`

**Closed by klaushauschild1984** 2021-03-18 08:37 UTC
Labels: enhancement
